-- Seed Vagabond chapters into D1 database

INSERT INTO chapters (number, title, description, volume, page_count) VALUES
(1, 'The Sword', 'Musashi begins his journey as a young warrior.', 1, 45),
(2, 'First Blood', 'A fateful encounter tests Musashi''s resolve.', 1, 42),
(3, 'The Road', 'Musashi embarks on a wandering journey.', 1, 48),
(4, 'A Duel', 'Musashi faces a rival swordsman.', 1, 50),
(5, 'The Master', 'Musashi seeks training from a sensei.', 1, 46),
(6, 'Growing Pains', 'Training takes its toll on mind and body.', 1, 44),
(7, 'Discipline', 'Musashi learns the importance of discipline.', 2, 47),
(8, 'The Dojo', 'Musashi trains at a renowned dojo.', 2, 49),
(9, 'Victory', 'Musashi''s first major victory.', 2, 45),
(10, 'Recognition', 'Musashi''s name spreads across the land.', 2, 43),
(11, 'The Challenge', 'A powerful warrior challenges Musashi.', 2, 51),
(12, 'Preparation', 'Musashi prepares for the coming battle.', 2, 46),
(13, 'The Battle', 'An intense duel determines Musashi''s future.', 2, 52),
(14, 'After Victory', 'Musashi reflects on his triumph.', 3, 44),
(15, 'Redemption', 'Musashi seeks to atone for past mistakes.', 3, 48),
(16, 'The Wanderer', 'Musashi continues as a lone swordsman.', 3, 45),
(17, 'A Village', 'Musashi finds refuge in a quiet village.', 3, 47),
(18, 'Connection', 'Musashi forms an unexpected bond.', 3, 43),
(19, 'The Past', 'Musashi''s dark past catches up with him.', 3, 49),
(20, 'Departure', 'Musashi must leave the village.', 3, 46),
(21, 'Mountains', 'Musashi seeks solitude in the mountains.', 4, 50),
(22, 'Meditation', 'Deep meditation reveals new insights.', 4, 45),
(23, 'Enlightenment', 'A moment of clarity transforms Musashi.', 4, 48),
(24, 'Return', 'Musashi descends from the mountains changed.', 4, 44),
(25, 'New Strength', 'Musashi demonstrates unprecedented skill.', 4, 51),
(26, 'The Enemy', 'An old enemy emerges from his past.', 4, 47),
(27, 'Confrontation', 'Musashi faces his nemesis at last.', 4, 52),
(28, 'Mercy', 'Musashi chooses a path beyond violence.', 5, 46),
(29, 'Legacy', 'Musashi''s actions shape the future.', 5, 43),
(30, 'Serenity', 'Musashi finally finds inner peace.', 5, 49),
(31, 'Harmony', 'Musashi''s mastery extends beyond the sword.', 5, 45),
(32, 'Art', 'Musashi explores art and combat.', 5, 47),
(33, 'Philosophy', 'Musashi contemplates existence.', 5, 44),
(34, 'Teaching', 'Musashi shares his knowledge with others.', 6, 48),
(35, 'Disciples', 'Musashi takes on talented students.', 6, 46),
(36, 'The Young Warrior', 'A promising fighter seeks Musashi''s guidance.', 6, 50),
(37, 'Training', 'Musashi puts his student through rigorous training.', 6, 52),
(38, 'Trial', 'The student faces their first true test.', 6, 45),
(39, 'Growth', 'The student understands Musashi''s teachings.', 6, 47),
(40, 'Journey Together', 'Master and student travel side by side.', 6, 49),
(41, 'Conflict', 'Master and student''s philosophies clash.', 7, 44),
(42, 'Separation', 'The student must forge their own path.', 7, 46),
(43, 'Solitude', 'Musashi returns to his wandering.', 7, 48),
(44, 'Memory', 'Musashi remembers those from his past.', 7, 45),
(45, 'The Temple', 'Musashi seeks refuge in a sacred temple.', 7, 47),
(46, 'Wisdom', 'Monks share ancient teachings with Musashi.', 7, 51),
(47, 'Doubt', 'Musashi questions everything he learned.', 7, 43),
(48, 'Crisis', 'Musashi faces a spiritual crisis.', 8, 50),
(49, 'Descent', 'Musashi''s mind and spirit unravel.', 8, 49),
(50, 'Exile', 'Musashi faces consequences of his past.', 8, 46),
(51, 'Darkness', 'Musashi descends into darkness.', 8, 52),
(52, 'Rock Bottom', 'Musashi reaches his lowest point.', 8, 44),
(53, 'The Light', 'Hope appears in Musashi''s darkness.', 8, 47),
(54, 'Awakening', 'Musashi rises from his despair.', 8, 45),
(55, 'Rebirth', 'Musashi is born anew from his ashes.', 9, 48),
(56, 'Healing', 'Musashi begins the process of healing.', 9, 46),
(57, 'Strength', 'Musashi regains his strength.', 9, 50),
(58, 'Purpose', 'Musashi discovers his new purpose.', 9, 43),
(59, 'The Way', 'Musashi walks a new path forward.', 9, 49),
(60, 'Destiny', 'Musashi''s path and destiny converge.', 9, 47),
(61, 'The Town', 'Musashi arrives in a bustling town.', 9, 45),
(62, 'Society', 'Musashi navigates society''s complexities.', 10, 51),
(63, 'Conflict', 'Musashi clashes with powerful forces.', 10, 48),
(64, 'Alliance', 'Musashi forms unexpected alliances.', 10, 46),
(65, 'Battle', 'A grand battle tests Musashi''s resolve.', 10, 52),
(66, 'Victory', 'Musashi emerges victorious but changed.', 10, 44),
(67, 'Consequence', 'Musashi faces the consequences of his actions.', 10, 49),
(68, 'Regret', 'Musashi wrestles with regret and remorse.', 10, 47),
(69, 'Acceptance', 'Musashi learns to accept his past.', 10, 45),
(70, 'Peace', 'Musashi finally finds peace within.', 10, 50),
(71, 'The Ocean', 'Musashi visits the vast ocean.', 10, 46),
(72, 'Reflection', 'Musashi reflects on his entire journey.', 10, 48),
(73, 'Gratitude', 'Musashi expresses gratitude for all.', 10, 43),
(74, 'Connection', 'Musashi reconnects with his past.', 10, 51),
(75, 'Forgiveness', 'Musashi seeks and grants forgiveness.', 10, 47),
(76, 'Legacy', 'Musashi contemplates his legacy.', 10, 49),
(77, 'The Scroll', 'Musashi writes his teachings and philosophy.', 10, 45),
(78, 'Words', 'Musashi''s written wisdom comes to life.', 10, 48),
(79, 'Transmission', 'Musashi passes knowledge to others.', 10, 46),
(80, 'The Next', 'A new warrior begins their journey.', 10, 44),
(81, 'Spring', 'Musashi enjoys the beauty of spring.', 10, 50),
(82, 'Growth', 'New life sprouts around Musashi.', 10, 47),
(83, 'Summer', 'Musashi experiences the heat of summer.', 10, 49),
(84, 'Intensity', 'Life reaches its peak intensity.', 10, 45),
(85, 'Autumn', 'Musashi witnesses the fall of leaves.', 10, 51),
(86, 'Letting Go', 'Musashi learns to let go.', 10, 43),
(87, 'Winter', 'Musashi faces the harshness of winter.', 10, 48),
(88, 'Stillness', 'Everything becomes quiet and still.', 10, 46),
(89, 'Eternity', 'Musashi touches the infinite.', 10, 52),
(90, 'The Circle', 'The journey completes its circle.', 10, 44),
(91, 'Echoes', 'Musashi hears echoes of past and future.', 10, 49),
(92, 'Convergence', 'All paths converge toward a final moment.', 10, 47),
(93, 'Clarity', 'Perfect clarity emerges from Musashi.', 10, 45),
(94, 'The Duel', 'Musashi''s greatest duel awaits.', 10, 50),
(95, 'Perfection', 'Musashi achieves perfect technique.', 10, 48),
(96, 'Transcendence', 'Musashi transcends mortal combat.', 10, 46),
(97, 'Beyond', 'Musashi goes beyond imagination.', 10, 51),
(98, 'Eternity', 'Musashi becomes one with eternity.', 10, 47),
(99, 'The End', 'Everything draws to a close.', 10, 49),
(100, 'Enlightenment', 'Musashi achieves spiritual awakening and mastery.', 10, 55);
