-- Migration: Seed data from legacy database

-- Step 1: Insert author (Takehiko Inoue)
INSERT INTO authors (name) VALUES ('Takehiko Inoue');

-- Step 2: Insert manga (Vagabond)
INSERT INTO mangas (author_id, artist_id, title, description, status)
VALUES (
  1,
  1,
  'Vagabond',
  'Striving for enlightenment by way of the sword, Miyamoto Musashi is prepared to cut down anyone who stands in his way. Vagabond is an action-packed portrayal of the life and times of the quintessential warrior-philosopher—the most celebrated samurai of all time!',
  'hiatus'
);

-- Step 3: Insert volumes (1-37)
INSERT INTO volumes (manga_id, number) VALUES (1, 1);
INSERT INTO volumes (manga_id, number) VALUES (1, 2);
INSERT INTO volumes (manga_id, number) VALUES (1, 3);
INSERT INTO volumes (manga_id, number) VALUES (1, 4);
INSERT INTO volumes (manga_id, number) VALUES (1, 5);
INSERT INTO volumes (manga_id, number) VALUES (1, 6);
INSERT INTO volumes (manga_id, number) VALUES (1, 7);
INSERT INTO volumes (manga_id, number) VALUES (1, 8);
INSERT INTO volumes (manga_id, number) VALUES (1, 9);
INSERT INTO volumes (manga_id, number) VALUES (1, 10);
INSERT INTO volumes (manga_id, number) VALUES (1, 11);
INSERT INTO volumes (manga_id, number) VALUES (1, 12);
INSERT INTO volumes (manga_id, number) VALUES (1, 13);
INSERT INTO volumes (manga_id, number) VALUES (1, 14);
INSERT INTO volumes (manga_id, number) VALUES (1, 15);
INSERT INTO volumes (manga_id, number) VALUES (1, 16);
INSERT INTO volumes (manga_id, number) VALUES (1, 17);
INSERT INTO volumes (manga_id, number) VALUES (1, 18);
INSERT INTO volumes (manga_id, number) VALUES (1, 19);
INSERT INTO volumes (manga_id, number) VALUES (1, 20);
INSERT INTO volumes (manga_id, number) VALUES (1, 21);
INSERT INTO volumes (manga_id, number) VALUES (1, 22);
INSERT INTO volumes (manga_id, number) VALUES (1, 23);
INSERT INTO volumes (manga_id, number) VALUES (1, 24);
INSERT INTO volumes (manga_id, number) VALUES (1, 25);
INSERT INTO volumes (manga_id, number) VALUES (1, 26);
INSERT INTO volumes (manga_id, number) VALUES (1, 27);
INSERT INTO volumes (manga_id, number) VALUES (1, 28);
INSERT INTO volumes (manga_id, number) VALUES (1, 29);
INSERT INTO volumes (manga_id, number) VALUES (1, 30);
INSERT INTO volumes (manga_id, number) VALUES (1, 31);
INSERT INTO volumes (manga_id, number) VALUES (1, 32);
INSERT INTO volumes (manga_id, number) VALUES (1, 33);
INSERT INTO volumes (manga_id, number) VALUES (1, 34);
INSERT INTO volumes (manga_id, number) VALUES (1, 35);
INSERT INTO volumes (manga_id, number) VALUES (1, 36);
INSERT INTO volumes (manga_id, number) VALUES (1, 37);

-- Step 4: Insert chapters (excluding 323-327)
-- Total: 322 chapters
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Shinmen Takezo', 1, 46, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Akemi', 2, 26, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Oko', 3, 22, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'The Brigand Tsujikaze', 4, 21, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Blood Game', 5, 19, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'The Troubles of Hon''iden Matahachi at Seventeen', 6, 21, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Farewell Takezo', 7, 24, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Miyamoto Village', 8, 20, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Fiancée', 9, 20, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 1), 'Left Behind', 10, 19, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Demon', 11, 23, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Takuan', 12, 19, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Life', 13, 21, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Cut Down', 14, 21, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'No Fear', 15, 22, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Captured', 16, 19, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Invincible Under the Sun', 17, 19, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Tree of Shame', 18, 22, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'The Demon''s Child', 19, 22, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'Death', 20, 20, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 2), 'A Place in the Sun', 21, 21, 922165200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'Miyamoto Musashi', 22, 20, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'First Step', 23, 20, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'The Challenge', 24, 21, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'Chaos at the Yoshioka School', 25, 25, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'The Master', 26, 24, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'Instinct', 27, 21, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'Demon II', 28, 21, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'Ignorance', 29, 22, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'A Single Stroke', 30, 21, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 3), 'Inferno', 31, 29, 932619600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Wanderers', 32, 29, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Departures', 33, 21, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Departures II', 34, 19, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Distraction', 35, 22, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Hozoin', 36, 21, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Bloodthirst', 37, 21, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Graceless', 38, 21, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Inshun', 39, 26, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 4), 'Agon', 40, 19, 940568400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'The Assassin', 41, 21, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'Howl', 42, 19, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'Inshun''s Spear', 43, 24, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'Life', 44, 21, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'Unease', 45, 21, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'The Demon Within', 46, 21, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'Fear', 47, 19, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'Fear II', 48, 19, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 5), 'Fear III', 49, 23, 948430800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Surviving', 50, 21, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Lying Low', 51, 20, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Lying Low II', 52, 21, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Journey', 53, 20, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Vision', 54, 21, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'The Decision of a Formerly Kept Man', 55, 22, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Osaka', 56, 20, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Vermin', 57, 20, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Sasaki Kojiro', 58, 22, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 6), 'Hozoin Pickles', 59, 29, 956293200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'Duel''s Eve', 60, 24, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'Duel''s Eve II', 61, 20, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'Dawn', 62, 19, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'Spider''s Thread', 63, 19, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'Heaven and Earth', 64, 19, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'Legacy', 65, 18, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'The Master', 66, 20, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'Kami''izumi Ise no Kami Hidetsuna', 67, 21, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 7), 'No Sword', 68, 18, 964155600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Life II', 69, 19, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Life III', 70, 17, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Inshun', 71, 18, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Shinnosuke', 72, 22, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Playing in the Sand', 73, 21, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Sudden Storm', 74, 20, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Survivors', 75, 19, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Don''t Put Your Life on the Line', 76, 18, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'They Call Me Sensei', 77, 19, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 8), 'Ascending Dragon', 78, 21, 972277200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'The Yagyu', 79, 22, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'Coming Home', 80, 20, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'The Peony Messenger', 81, 21, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'Successor to the Invincible', 82, 22, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'Legacy', 83, 20, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'Promise', 84, 21, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'Ship of Stone', 85, 21, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'A Round of Discussion', 86, 20, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 9), 'Provocateur', 87, 31, 982731600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'Disciple', 88, 23, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'One Man Battle', 89, 20, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'The Battle', 90, 20, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'Bamboo Flute', 91, 19, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'The Four Senior Disciples', 92, 21, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'Valor', 93, 18, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'Retribution', 94, 22, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'Longing', 95, 17, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'Reunion', 96, 18, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 10), 'Sliding Door', 97, 20, 990594000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'Unrivaled', 98, 20, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'Son of the Invincible', 99, 18, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'The Real Thing', 100, 19, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'Blue Sky', 101, 21, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'The Infinite Universe', 102, 19, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'Farewell at Dawn', 103, 20, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'Autumn Sky', 104, 20, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'Journey', 105, 22, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'Footprints', 106, 19, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 11), 'The Road to Ise', 107, 20, 998283600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Summit', 108, 22, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Sea of Clouds', 109, 20, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Uncle Gon', 110, 21, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Lowlife', 111, 22, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Mother', 112, 19, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Osugi''s Ordeal', 113, 22, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'He and I', 114, 20, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Apparition', 115, 20, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Baiken', 116, 18, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 12), 'Chain and Sickle', 117, 28, 1006405200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Rindo', 118, 22, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'The Girl and the God of Death', 119, 20, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'The Resurrection of the God of Death', 120, 20, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Two Swords', 121, 18, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Moths', 122, 15, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Akebi Fruit', 123, 20, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Connections', 124, 19, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Spiral', 125, 19, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Special: Tsujikaze Kohei: Part One', 126, 22, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 13), 'Special: Tsujikaze Kohei: Part Two', 127, 21, 1016773200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'The Letter', 128, 22, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'Hands', 129, 22, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'Glimmering Waves', 130, 22, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'Seaweed', 131, 21, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'Fate', 132, 21, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'To Live by the Sword', 133, 24, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'Driftwood', 134, 22, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'The Plan', 135, 22, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 14), 'Kojiro and Tenki', 136, 21, 1024635600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 15), 'A Gift from the Sea', 137, 32, 1035349200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 15), 'Farewell, Kojiro', 138, 27, 1035349200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 15), 'Butterfly', 139, 28, 1035349200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 15), 'Flames', 140, 27, 1035349200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 15), 'Sword Against Sword', 141, 27, 1035349200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 15), 'Savior', 142, 27, 1035349200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 15), 'The Kanemaki Dojo', 143, 34, 1035349200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 16), 'Master and Pupil', 144, 31, 1045803600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 16), 'The Fifth Year of Keicho (1600)', 145, 22, 1045803600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 16), 'Senior Disciple', 146, 26, 1045803600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 16), 'Jisai''s Cocoon', 147, 26, 1045803600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 16), 'Tiger', 148, 26, 1045803600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 16), 'Blood Bath', 149, 26, 1045803600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 16), 'Mad Tiger', 150, 25, 1045803600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 17), 'Numb', 151, 26, 1056344400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 17), 'Brothers', 152, 27, 1056344400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 17), 'Blood Battle', 153, 26, 1056344400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 17), 'Shore of Blood', 154, 24, 1056344400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 17), 'The Departure', 155, 21, 1056344400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 17), 'A Complete Life', 156, 25, 1056344400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 17), 'Ganryu', 157, 25, 1056344400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 18), 'Muso Gonnosuke', 158, 28, 1069304400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 18), 'The Stage', 159, 27, 1069304400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 18), 'Battlefield', 160, 26, 1069304400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 18), 'Those Who Defy Death', 161, 25, 1069304400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 18), 'Rampage of the Beast', 162, 25, 1069304400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 18), 'Six O''clock at Sekigahara', 163, 26, 1069304400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 18), 'Refugee Hunters', 164, 34, 1069304400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 19), 'Death Torches', 165, 30, 1080018000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 19), 'First Friend', 166, 25, 1080018000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 19), 'Mountain of Shattered Dreams', 167, 26, 1080018000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 19), 'Over the Mountain', 168, 26, 1080018000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 19), 'The Distant Ocean', 169, 24, 1080018000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 19), 'Strands of the Departed', 170, 26, 1080018000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 19), 'The Sword', 171, 26, 1080018000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'Sons', 172, 26, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'The Desire to Fight', 173, 27, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'Ichizō', 174, 25, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'Younger Brother', 175, 28, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'Open Mind', 176, 24, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'Koun and Kojirō', 177, 25, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'Koun and Kojirō Part II', 178, 21, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 20), 'Koun and Kojirō Part III', 179, 20, 1090558800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'Gathering in Kyoto', 180, 37, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'Carving Demons', 181, 24, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'First Snow', 182, 22, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'The Same Moon', 183, 21, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'Eagle and Ant', 184, 22, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'Rendaiji', 185, 19, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'Altercation After Dark', 186, 20, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'Before Dawn', 187, 21, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 21), 'A Place to Exist', 188, 30, 1127278800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'Burdened', 189, 25, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'The Death of Seijuro', 190, 20, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'Painting with Water', 191, 21, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'Koetsu and Myoshu', 192, 21, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'Bedlam in Kyoto', 193, 22, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'Talk of the Town', 194, 21, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'Confrontation of Rivals', 195, 21, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'Return of the Vainglorious', 196, 20, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 22), 'The Real Kojiro', 197, 22, 1140670800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Grass, Snow, and Blood', 198, 28, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Kojiro and Matahachi', 199, 24, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Two Kojiros', 200, 21, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Ladder to Success', 201, 23, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Presumptuous', 202, 18, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'The Day After Tomorrow', 203, 22, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Sword Sharpening', 204, 22, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Sottaku', 205, 21, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 23), 'Straightforward', 206, 21, 1151038800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'Afternoon Nap', 207, 27, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'Chance Encounter', 208, 23, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'A Long Detour', 209, 22, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'Rivals at Play', 210, 18, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'On the Eve of Battle', 211, 21, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'Bright New Morning', 212, 17, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'Worthless Junk', 213, 21, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'Rengeoin', 214, 21, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 24), 'It''s Already Begun', 215, 28, 1161579600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'A Year After', 216, 29, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'Denshichirō Advances', 217, 22, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'Demise', 218, 25, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'Unbreakable Bonds', 219, 16, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'Admiration and Hate', 220, 22, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'Old Friends', 221, 18, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'Friends', 222, 22, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'From the Treetop', 223, 20, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 25), 'Ichijōji Sagarimatsu', 224, 22, 1174626000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'Musashi Against Seventy Samurai', 225, 27, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'Debt to the Yoshioka', 226, 16, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'Army of One', 227, 18, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'Swarm', 228, 21, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'The Rapids', 229, 21, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'Sallowed Sky', 230, 19, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'Exhaustion', 231, 19, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'Life', 232, 20, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 26), 'It Finds a Way', 233, 19, 1185166800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'The Onslaught', 234, 23, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'The Depth', 235, 20, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'Battle Threshold', 236, 20, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'Somewhere Along the Way', 237, 18, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'Changing Times', 238, 20, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'Blood-Stained Mud', 239, 21, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'An Auspicious Encounter', 240, 19, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'One Sword', 241, 21, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 27), 'Battle''s End', 242, 40, 1196312400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'Frogs', 243, 28, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'The Solitary Way', 244, 22, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'Reunion', 245, 17, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'Nothing''s Changed', 246, 22, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'While You Sleep', 247, 19, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'Pulse', 248, 20, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'The Man in the Rumors', 249, 21, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'An End to Fighting', 250, 22, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 28), 'Prayer', 251, 25, 1211518800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'An Imprisoned Musashi', 252, 24, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'To Live by the Sword', 253, 15, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'Home', 254, 22, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'Questions', 255, 21, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'Voices', 256, 20, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'Contradiction', 257, 24, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'The Glowing Light in the Depths', 258, 18, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'Still the Stick', 259, 22, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 29), 'The Flames of Hatred', 260, 21, 1227848400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'Moonlight', 261, 25, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'Separation', 262, 19, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'The Facts of a Dream', 263, 21, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'Heat Haze', 264, 21, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'Just That Much', 265, 21, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'Fragments', 266, 22, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'Crossroads', 267, 21, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'On the Edge of the Sword', 268, 21, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 30), 'Light', 269, 32, 1243486800);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'Vagabond', 270, 29, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'The Shadow of the Spiral', 271, 22, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'Dreams Worn Out and Returning Home', 272, 22, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'Mother and Child', 273, 22, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'Mother', 274, 19, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'Liar', 275, 23, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'A Chance Meeting', 276, 18, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'A Friend', 277, 21, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 31), 'Treasure', 278, 21, 1251954000);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'Aspiration', 279, 28, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'Ittousai, The Demon Swordsman', 280, 21, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'A Great Man Falls', 281, 21, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'This Form', 282, 21, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'Thirteen Years Old', 283, 17, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'The Spiral', 284, 20, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'Learning to Smile', 285, 20, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'Tiger and Tiger', 286, 14, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 32), 'The Way Without a Blade', 287, 28, 1263531600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'Kokura', 288, 26, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'The Music Inside', 289, 22, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'The World of People', 290, 20, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), '7 Years', 291, 18, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'Profile', 292, 22, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'Haze', 293, 22, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'Give It Up', 294, 33, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'Paper Balloon', 295, 17, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 33), 'Kojiro''s City', 296, 31, 1274936400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 34), 'The Flower of Kakura', 297, 32, 1350968400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 34), 'Instructor', 298, 19, 1350968400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 34), 'Mogura', 299, 21, 1350968400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 34), 'The Future of Our Freedom', 300, 17, 1350968400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 34), 'At The End of The Journey', 301, 43, 1350968400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 34), 'Children of the Earth', 302, 39, 1350968400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 34), 'Rainy Soil', 303, 37, 1350968400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 35), 'Overflowing Water', 304, 37, 1366693200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 35), 'The Water Path', 305, 37, 1366693200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 35), 'Infinite Smiles', 306, 35, 1366693200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 35), 'The Tip', 307, 38, 1366693200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 35), 'Locusts', 308, 37, 1366693200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 35), 'Earth', 309, 37, 1366693200);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 36), 'Late Autumn', 310, 38, 1382504400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 36), 'A Lively Life', 311, 36, 1382504400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 36), 'The Fool''s Paddy Field', 312, 30, 1382504400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 36), 'A Corpse and Lives', 313, 29, 1382504400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 36), 'Breath', 314, 35, 1382504400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 36), 'When the Water Warms', 315, 47, 1382504400);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 37), 'Spring Thunder', 316, 40, 1406091600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 37), 'Pure and Clear', 317, 35, 1406091600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 37), 'Rice Seedlings', 318, 29, 1406091600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 37), 'Something Frail', 319, 24, 1406091600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 37), 'Footpath', 320, 29, 1406091600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 37), 'Shusaku Collapses', 321, 30, 1406091600);
INSERT INTO chapters (volume_id, title, number, page_count, release_date) VALUES ((SELECT id FROM volumes WHERE number = 37), 'Dragonflies', 322, 35, 1406091600);